#!/bin/bash
#PBS -S /bin/bash
#PBS -l nodes=1:ppn=1
#PBS -l walltime=10:00:00
##--PBS -l pmem=1000mb

cd $PBS_O_WORKDIR
echo "Current working directory is `pwd`"
echo "Node file: $PBS_NODEFILE :"
echo "---------------------"
cat $PBS_NODEFILE
echo "---------------------"
PBS_NP=`/bin/awk 'END {print NR}' $PBS_NODEFILE`
echo "Running on $PBS_NP processors."

echo "Starting run at: `date`"
pdbname1=($pdbname)
#blastp -query 1abs.fasta -db nr -evalue 1e-5 -num_threads 8
for i in {0..99}
do
f=${pdbname1[$i]}
name=${f:(-4)}
echo $name
echo $f
mview $f -out fasta | sed 's/-//g' > seqs/$name
done

echo "Job3 finished at: `date`"
